image: maven

stages:
- build
- test

build:  
  stage: build
  script:
  - mvn package -Dmaven.test.skip

test:
  stage: test
  script:
  - echo "Olá Alunos"
  - echo "Da Turma 2 IBM"
  - echo "If Black Then Code"


