name: CI_IBM

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Validando o Pacote JAVA
      run: - mvn package -Dmaven.test.skip

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Roda o Teste de Unidade
      run: - mvn test